version: 2.1
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x .scripts/repo-sync.sh
            shellcheck -x .scripts/gen_packages.sh
            shellcheck -x .scripts/index_repo.sh
            shellcheck -x .test/lint-charts.sh
            shellcheck -x .test/e2e-kind.sh
            
  lint-charts:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.2.0
      CHARTS_REPO: https://github.com/rimusz/charts
    steps:
      - checkout
      - run:
          name: install
          command: .test/lint-charts.sh
          
  install-charts:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.2.0
      CHARTS_REPO: https://github.com/rimusz/charts
      K8S_VERSION: v1.13.4
      KIND_VERSION: 0.2.0
    steps:
      - checkout
      - run:
          name: install
          command: .test/e2e-kind.sh
          no_output_timeout: 3600
          
workflows:
  version: 2
  lint_and_install:
    jobs:
      - lint-scripts
      - lint-charts:
          requires:
            - lint-scripts
      - install-charts:
          requires:
            - lint-charts
