version: 2.1
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: run-lint
          command: |
            shellcheck -x .test/e2e-kind.sh
            shellcheck -x .test/lint-charts-local.sh
            shellcheck -x .test/e2e-docker4mac.sh
            shellcheck -x .test/e2e-local-gke.sh
            
  lint-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:v2.3.3
    steps:
      - checkout
      - run:
          name: run-lint
          command: ct lint --config .test/ct.yaml
          
  install-charts:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.3.3
      CHARTS_REPO: https://github.com/rimusz/charts
      K8S_VERSION: v1.14.2
      KIND_VERSION: v0.3.0
    steps:
      - checkout
      - run:
          name: run-install
          command: .test/e2e-kind.sh
          no_output_timeout: 3600
          
workflows:
  version: 2
  lint_and_install:
    jobs:
      - lint-scripts
      - lint-charts:
          requires:
            - lint-scripts
      - install-charts:
          requires:
            - lint-charts
